name: "Deploy App"

on:
  push:
    tags:
      - "deploy/v*"

env:
  PROJECT_PATH: weirditor.csproj
  PUBLISH_DIR: bin/Release/net9.0-windows/publish

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x

      - name: Restore Dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Publish Project
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -r win-x64 --self-contained -p:PublishSingleFile=true -o ${{ env.PUBLISH_DIR }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.FINE_GRAINED_PAT }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - name: Upload Release Asset
        uses: csexton/release-asset-action@v2
        with:
          github-token: ${{ secrets.FINE_GRAINED_PAT }}
          pattern: ${{ env.PUBLISH_DIR }}/*.exe
          release-url: ${{ steps.create_release.outputs.upload_url }}
